/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package garage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Georgette Gabou
 */
public class Planning extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form Planning
     */
    public Planning() {
        initComponents();
//        try {
//            Table1();
//        } catch (SQLException ex) {
//            Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    public void Table1() throws SQLException{
        try{
    Connexion co = new Connexion();
        Connection con;
        try{
    con= co.connect();
    String columns[]= new String[] {"idIntervention", "Date", "typeIntervention",  "Description", "Immatriculation", "Nom"};
        String[] data= new String[6];
        model= new DefaultTableModel(null,columns);
        String query5= "SELECT * FROM intervention"; //WHERE ( idMecanicien= ?);
        PreparedStatement stat = con.prepareStatement(query5) ;
        
        //stat.setString(1,c);
        //stat.setString(2,a);
        ResultSet rs = stat.executeQuery() ;
       // int i=0;
        while(rs.next()){
            String nom=rs.getString("idIntervention");
            String prenom= rs.getString("Date");
            String d = rs.getString("typeIntervention");
          
            String pp=rs.getString("Description");
            String m=rs.getString("Immatriculation");
            String m22=rs.getString("Nom");
//            
           
            data[0]=nom;
            data[1]=prenom;
            data[2]=d;  
                       
            data[3]=pp;
            data[4]=m;
            data[5]=m22; 
          
            model.addRow(data);
        }
        jTable2.setModel(model);
        stat.close();
        con.close();
        }catch (ClassNotFoundException ex) {
                Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
        }
    }catch(SQLException e){
            e.printStackTrace();
    }
    
//    try{
//    Connexion co = new Connexion();
//        Connection con;
//        try{
//    con= co.connect();
//    String columns[]= new String[] {"idIntervention", "Date", "typeIntervention", "idMecanicien", "Description", "Immatriculation"};
//        String[] data= new String[6];
//        model= new DefaultTableModel(null,columns);
//        String query5= "SELECT * FROM intervention"; //WHERE ( idMecanicien= ?);
//        PreparedStatement stat = con.prepareStatement(query5) ;
//        
//        //stat.setString(1,c);
//        //stat.setString(2,a);
//        ResultSet rs = stat.executeQuery() ;
//        int i=0;
//        while(rs.next()){
//            String nom=rs.getString("idIntervention");
//            String prenom= rs.getString("Date");
//            String d = rs.getString("typeIntervention");
//            String m22=rs.getString("idMecanicien");
//            String m2=rs.getString("Description");
//            String m=rs.getString("Immatriculation");
////            
//           
//            data[0]=nom;
//            data[1]=prenom;
//            data[2]=d;  
//            data[3]=m22;            
//            data[4]=m2;
//            data[5]=m;
//          
//            model.addRow(data);
//        }
//        jTable2.setModel(model);
//        stat.close();
//        con.close();
//        }catch (ClassNotFoundException ex) {
//                Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
//        }
//    }catch(SQLException e){
//            e.printStackTrace();
//    }
//    }else{
//        System.out.println("Aucun élément sélectionné dans la liste déroulante");
//    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("BIENVENUE DANS L'INTERFACE DE VISUALISEATION");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("DES INTERVENTIONS");

        jToggleButton1.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jToggleButton1.setText("Visualiser le planning des mecaniciens");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel3.setText("CLIQUER SUR LE BUTON VISUALISER");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idIntervention", "Date", "typeIntervention", "idMecanicien", "Description", "Immatriculation"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jToggleButton2.setText("RETOUR");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(279, 279, 279))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jToggleButton1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jToggleButton2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
//        int ligne = jTable2.getSelectedRow();
//        List<String> liste = new ArrayList<>();
//        for (int i = 0; i < jTable2.getColumnCount(); i++) {
//            liste.add("" + jTable2.getValueAt(ligne, i));
//        }
//        jTextField1.setText(liste.get(0));
//        jTextField2.setText(liste.get(1));
//        jTextField3.setText(liste.get(2));
//        jTextArea1.setText(liste.get(3));
        //jComboBox2.setToolTipText(liste.get(4));
    }//GEN-LAST:event_jTable2MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Table1();
        } catch (SQLException ex) {
            Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         Accueil1 n = new Accueil1();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
