/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package garage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import com.itextpdf.kernel.pdf.PdfDocument;
//   import com.itextpdf.kernel.pdf.PdfWriter;
//   import com.itextpdf.layout.Document;
//   import com.itextpdf.layout.element.Paragraph;

   import javax.swing.*;
   import java.awt.event.ActionEvent;
   import java.awt.event.ActionListener;


/**
 *
 * @author Georgette Gabou
 */
public class RapportMecano extends javax.swing.JFrame {

    /**
     * Creates new form RapportMecano
     */
    public RapportMecano() {
        initComponents();
        try {
        recupererinformations();
        recupererinformations1();
        recupererinformations2();
        
            recupererinformations3();
        } catch (SQLException ex) {
            Logger.getLogger(RapportMecano.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RapportMecano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void recupererinformations() throws SQLException, ClassNotFoundException {

        try {
            Connexion co = new Connexion();
            Connection con = co.connect();



            PreparedStatement stat = con.prepareStatement("select Nom from mecanicien");
            ResultSet rs = stat.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("Nom"));
            }if (jComboBox1.getItemCount() > 0){
                jComboBox1.setSelectedIndex(0);
            }

        } catch (SQLException e) {
            System.out.println("ERREUR" + e.getMessage());

        }

    }
    
    private void recupererinformations1() throws SQLException, ClassNotFoundException {

        try {
            Connexion co = new Connexion();
            Connection con = co.connect();



            PreparedStatement stat = con.prepareStatement("select NomClient from client");
            ResultSet rs = stat.executeQuery();
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("NomClient"));
            }if (jComboBox2.getItemCount() > 0){
                jComboBox2.setSelectedIndex(0);
            }

        } catch (SQLException e) {
            System.out.println("ERREUR" + e.getMessage());

        }

    }
    private void recupererinformations2() throws SQLException, ClassNotFoundException {

        try {
            Connexion co = new Connexion();
            Connection con = co.connect();



            PreparedStatement stat = con.prepareStatement("select Immatriculation from intervention");
            ResultSet rs = stat.executeQuery();
            while (rs.next()) {
                jComboBox3.addItem(rs.getString("Immatriculation"));
            }if (jComboBox3.getItemCount() > 0){
                jComboBox3.setSelectedIndex(0);
            }

        } catch (SQLException e) {
            System.out.println("ERREUR" + e.getMessage());

        }

    }
    
    private void recupererinformations3() throws SQLException, ClassNotFoundException {

        try {
            Connexion co = new Connexion();
            Connection con = co.connect();



            PreparedStatement stat = con.prepareStatement("select typeIntervention from intervention");
            ResultSet rs = stat.executeQuery();
            while (rs.next()) {
                jComboBox4.addItem(rs.getString("typeIntervention"));
            }if (jComboBox4.getItemCount() > 0){
                jComboBox4.setSelectedIndex(0);
            }

        } catch (SQLException e) {
            System.out.println("ERREUR" + e.getMessage());

        }

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("WELCOME USER!!!!");

        jLabel2.setText("Identifiant Du rapport");

        jLabel3.setText("Nom du mecanicien");

        jLabel4.setText("Nom du client");

        jLabel5.setText("Immatriculation du vehicule du client :");

        jLabel6.setText("Nombre de pieces utilises :");

        jLabel7.setText("Type d'intervention :");

        jLabel8.setText("Details de la reparation : ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("Enregistrer");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Imprimer rapport");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("RETOUR");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jToggleButton3)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 189, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String nom = jTextField1.getText();
        String mdp = jTextField2.getText();
        String l = jTextArea1.getText();
        //String l = jTextField4.getText();
        String n = jComboBox1.getSelectedItem().toString();
        String q = jComboBox2.getSelectedItem().toString();
        String q1 = jComboBox3.getSelectedItem().toString();
        String q2 = jComboBox4.getSelectedItem().toString();
        //Syste.out.println(l);
        //Syste.out.println(l);
        
        if (nom.equals("") && mdp.equals("") && l.equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer les informations du rapport!!!", "Informations incorrectes", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                Connexion co = new Connexion();
                Connection con = null;
                try {
                    con = co.connect();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
                }

                String query2 = "INSERT INTO rapport (idRapport, Nom, NomClient, Immatriculation, typeIntervention, Nbrepieces, Details) VALUES (?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(query2);
                pst.setString(1, nom);
                pst.setString(2, n);
                //pst.setString(3, marq); 
                pst.setString(3, q);
                pst.setString(4, q1);
                pst.setString(5, q2);
                pst.setString(6, mdp);
                pst.setString(7, l);
               
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Rapport enregistré avec succes!");

            } catch (SQLException ex) {
                Logger.getLogger(getName()).log(Level.SEVERE, null, ex);
            }
            //decharger();
        }
        //Table1();
                                   
                             
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        
            Accueil1Mecano n = new Accueil1Mecano();
            
            n.setVisible(true);
            dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    String identifiant = jTextField1.getText();
    String nombrePieces = jTextField2.getText();
    String details = jTextArea1.getText();
    String mecanicien = (String) jComboBox1.getSelectedItem();
    String client = (String) jComboBox2.getSelectedItem();
    String vehicule = (String) jComboBox3.getSelectedItem();
    String intervention = (String) jComboBox4.getSelectedItem();

        //String vehicule = (String) jComboBox3.getSelectedItem();
            // Ouvrir un sélecteur de fichier pour choisir où enregistrer le PDF
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Choisir l'emplacement pour enregistrer le rapport");
    fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);

    // Ajouter une extension par défaut au fichier
    fileChooser.setSelectedFile(new java.io.File("RapportMecanicien.pdf"));

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();
        String pdfFilePath = fileToSave.getAbsolutePath();
        
        // Ajouter l'extension ".pdf" si l'utilisateur ne l'a pas incluse
        if (!pdfFilePath.endsWith(".pdf")) {
            pdfFilePath += ".pdf";
        }

        // Générer le PDF
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        try {
            // Création du fichier PDF
            com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(pdfFilePath));
            document.open();

            // Ajouter un titre au document
            com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 18, com.itextpdf.text.Font.BOLD);
            com.itextpdf.text.Paragraph title = new com.itextpdf.text.Paragraph("Rapport de Réparation", titleFont);
            title.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            document.add(title);
            document.add(new com.itextpdf.text.Paragraph("\n")); // Ligne vide

            // Ajouter les informations au PDF
            com.itextpdf.text.Font contentFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 12);
            document.add(new com.itextpdf.text.Paragraph("Identifiant du Rapport : " + identifiant, contentFont));
            document.add(new com.itextpdf.text.Paragraph("Nom du Mécanicien : " + mecanicien, contentFont));
            document.add(new com.itextpdf.text.Paragraph("Nom du Client : " + client, contentFont));
            document.add(new com.itextpdf.text.Paragraph("Immatriculation du Véhicule : " + vehicule, contentFont));
            document.add(new com.itextpdf.text.Paragraph("Type d'Intervention : " + intervention, contentFont));
            document.add(new com.itextpdf.text.Paragraph("Nombre de Pièces Utilisées : " + nombrePieces, contentFont));
            document.add(new com.itextpdf.text.Paragraph("\nDétails de la Réparation : ", contentFont));
            document.add(new com.itextpdf.text.Paragraph(details, contentFont));

            // Ligne de fin
            document.add(new com.itextpdf.text.Paragraph("\n------------------------------", contentFont));
            document.add(new com.itextpdf.text.Paragraph("Fin du Rapport", contentFont));

            // Message de confirmation
            javax.swing.JOptionPane.showMessageDialog(this, "Rapport PDF généré avec succès : " + pdfFilePath);
        } catch (com.itextpdf.text.DocumentException | java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la génération du PDF : " + e.getMessage());
        } finally {
            document.close();
        }

        
    }else{
        javax.swing.JOptionPane.showMessageDialog(this, "Enregistrement annulé.");
    }


    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportMecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportMecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportMecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportMecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportMecano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
